// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220131173758_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            category = "Action/Adventure"
                        },
                        new
                        {
                            categoryId = 2,
                            category = "Fantasy/Action"
                        },
                        new
                        {
                            categoryId = 3,
                            category = "Sci-fi"
                        });
                });

            modelBuilder.Entity("Mission4.Models.MovieForm", b =>
                {
                    b.Property<int>("movieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("movieId");

                    b.HasIndex("categoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            movieId = 1,
                            categoryId = 1,
                            director = "Christopher Nolan",
                            edited = false,
                            rating = "PG-13",
                            title = "Inception",
                            year = 2010
                        },
                        new
                        {
                            movieId = 2,
                            categoryId = 2,
                            director = "Haruo Sotozaki",
                            edited = false,
                            note = "Watch TV show first",
                            rating = "R",
                            title = "Demon Slayer: Kimetsu no Yaiba – The Movie: Mugen Train",
                            year = 2020
                        },
                        new
                        {
                            movieId = 3,
                            categoryId = 3,
                            director = "George Lucas",
                            edited = false,
                            lentTo = "Mom",
                            rating = "PG",
                            title = "Star Wars: Episode IV - A New Hope",
                            year = 1977
                        });
                });

            modelBuilder.Entity("Mission4.Models.MovieForm", b =>
                {
                    b.HasOne("Mission4.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
